EXPECTED = {'functions': {'fold_freq': {'params': [('m', ('tensor', [('k', 'invariant')])),
                                        ('q', 'ℝ')],
                             'return_type': ('tensor', [('k', 'invariant')]),
                             'body': ('sub',
                                      ('var', 'm'),
                                      ('mul',
                                       ('call',
                                        'gt',
                                        [('var', 'm'),
                                         ('div', ('var', 'q'), ('num', 2))]),
                                       ('var', 'q'))),
                             'has_loop': False,
                             'statements': []},
               'structure_factor': {'params': [('nn1',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('nn2',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('nn3',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('cc', 'ℝ'),
                                               ('qx', 'ℝ'),
                                               ('qy', 'ℝ'),
                                               ('qz', 'ℝ')],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'body': ('call',
                                             'exp',
                                             [('mul',
                                               ('neg', ('imaginary',)),
                                               ('var', 'phase'))]),
                                    'has_loop': False,
                                    'statements': [('body_assign',
                                                    'phase',
                                                    ('mul',
                                                     ('var', 'cc'),
                                                     ('add',
                                                      ('add',
                                                       ('mul',
                                                        ('var', 'nn1'),
                                                        ('var', 'qx')),
                                                       ('mul',
                                                        ('var', 'nn2'),
                                                        ('var', 'qy'))),
                                                      ('mul',
                                                       ('var', 'nn3'),
                                                       ('var', 'qz')))))]}},
 'classes': {},
 'program': [('assign', 'a', ('num', 16.0), 5),
             ('assign', 'ecut', ('num', 16.0), 6),
             ('assign', 's1', ('num', 60), 7),
             ('assign', 's2', ('num', 60), 8),
             ('assign', 's3', ('num', 60), 9),
             ('assign',
              'n',
              ('mul', ('mul', ('var', 's1'), ('var', 's2')), ('var', 's3')),
              10),
             ('assign', 'px', ('num', 0.0), 12),
             ('assign', 'py', ('num', 0.0), 13),
             ('assign', 'pz', ('num', 0.0), 14),
             ('assign', 'ms', ('call', 'arange', [('var', 'n')]), 17),
             ('assign',
              'm1',
              ('call',
               'mod',
               [('call',
                 'floor',
                 [('div',
                   ('var', 'ms'),
                   ('mul', ('var', 's3'), ('var', 's2')))]),
                ('var', 's1')]),
              18),
             ('assign',
              'm2',
              ('call',
               'mod',
               [('call', 'floor', [('div', ('var', 'ms'), ('var', 's3'))]),
                ('var', 's2')]),
              19),
             ('assign',
              'm3',
              ('call', 'mod', [('var', 'ms'), ('var', 's3')]),
              20),
             ('func_def', 'fold_freq'),
             ('assign',
              'n1',
              ('call', 'fold_freq', [('var', 'm1'), ('var', 's1')]),
              26),
             ('assign',
              'n2',
              ('call', 'fold_freq', [('var', 'm2'), ('var', 's2')]),
              27),
             ('assign',
              'n3',
              ('call', 'fold_freq', [('var', 'm3'), ('var', 's3')]),
              28),
             ('assign',
              'c',
              ('div',
               ('mul', ('num', 2), ('num', 3.141592653589793)),
               ('var', 'a')),
              31),
             ('assign',
              'G2',
              ('mul',
               ('mul', ('var', 'c'), ('var', 'c')),
               ('add',
                ('add',
                 ('mul', ('var', 'n1'), ('var', 'n1')),
                 ('mul', ('var', 'n2'), ('var', 'n2'))),
                ('mul', ('var', 'n3'), ('var', 'n3')))),
              32),
             ('assign',
              'active',
              ('call',
               'le',
               [('var', 'G2'), ('mul', ('num', 2), ('var', 'ecut'))]),
              35),
             ('assign',
              'G2c',
              ('call', 'mask_select', [('var', 'G2'), ('var', 'active')]),
              36),
             ('func_def', 'structure_factor'),
             ('assign',
              'Sf',
              ('call',
               'structure_factor',
               [('var', 'n1'),
                ('var', 'n2'),
                ('var', 'n3'),
                ('var', 'c'),
                ('var', 'px'),
                ('var', 'py'),
                ('var', 'pz')]),
              43),
             ('assign',
              'Omega',
              ('mul', ('mul', ('var', 'a'), ('var', 'a')), ('var', 'a')),
              45),
             ('assign', 'count', ('call', 'sum', [('var', 'active')]), 46),
             ('expr', ('var', 'n'), 0),
             ('expr', ('var', 'Omega'), 0),
             ('expr', ('var', 'count'), 0),
             ('expr', ('index', 'G2', ('num', 0)), 0),
             ('expr', ('index', 'Sf', ('num', 0)), 0)]}
