EXPECTED = {'functions': {'coulomb': {'params': [('Z_nuc', 'ℝ'),
                                      ('G2', ('tensor', [('k', 'invariant')])),
                                      ('Sf', ('tensor', [('k', 'invariant')])),
                                      ('s1', 'ℕ'),
                                      ('s2', 'ℕ'),
                                      ('s3', 'ℕ')],
                           'return_type': ('tensor', [('k', 'invariant')]),
                           'body': ('call',
                                    'op_J',
                                    [('mul', ('var', 'Vcoul'), ('var', 'Sf')),
                                     ('var', 's1'),
                                     ('var', 's2'),
                                     ('var', 's3')]),
                           'has_loop': False,
                           'statements': [('body_assign',
                                           'pi',
                                           ('num', 3.141592653589793)),
                                          ('body_assign',
                                           'nonzero',
                                           ('call',
                                            'gt',
                                            [('var', 'G2'), ('num', 0.0)])),
                                          ('body_assign',
                                           'nonzero_f',
                                           ('mul',
                                            ('var', 'nonzero'),
                                            ('num', 1.0))),
                                          ('body_assign',
                                           'safe_G2',
                                           ('add',
                                            ('var', 'G2'),
                                            ('mul',
                                             ('sub',
                                              ('num', 1.0),
                                              ('var', 'nonzero_f')),
                                             ('num', 1.0)))),
                                          ('body_assign',
                                           'Vcoul',
                                           ('mul',
                                            ('div',
                                             ('mul',
                                              ('mul',
                                               ('neg', ('num', 4.0)),
                                               ('var', 'pi')),
                                              ('var', 'Z_nuc')),
                                             ('var', 'safe_G2')),
                                            ('var', 'nonzero_f')))]},
               'op_J': {'params': [('W', ('tensor', [('m', 'invariant')])),
                                   ('s1', 'ℕ'),
                                   ('s2', 'ℕ'),
                                   ('s3', 'ℕ')],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('div', ('var', 'flat'), ('var', 'n')),
                        'has_loop': False,
                        'statements': [('body_assign',
                                        'n',
                                        ('mul',
                                         ('mul', ('var', 's1'), ('var', 's2')),
                                         ('var', 's3'))),
                                       ('body_assign',
                                        'cube',
                                        ('call',
                                         'reshape',
                                         [('var', 'W'),
                                          ('var', 's1'),
                                          ('var', 's2'),
                                          ('var', 's3')])),
                                       ('body_assign',
                                        'spec',
                                        ('call', 'fft', [('var', 'cube')])),
                                       ('body_assign',
                                        'flat',
                                        ('call',
                                         'reshape',
                                         [('var', 'spec'), ('var', 'n')]))]}},
 'classes': {},
 'program': [('func_def', 'op_J'),
             ('func_def', 'coulomb'),
             ('assign', 's1', ('num', 2), 21),
             ('assign', 's2', ('num', 2), 22),
             ('assign', 's3', ('num', 2), 23),
             ('assign', 'n', ('num', 8), 24),
             ('assign', 'ms', ('call', 'arange', [('var', 'n')]), 25),
             ('assign',
              'm1',
              ('call',
               'mod',
               [('call', 'floor', [('div', ('var', 'ms'), ('num', 4.0))]),
                ('num', 2.0)]),
              26),
             ('assign',
              'm2',
              ('call',
               'mod',
               [('call', 'floor', [('div', ('var', 'ms'), ('num', 2.0))]),
                ('num', 2.0)]),
              27),
             ('assign',
              'm3',
              ('call', 'mod', [('var', 'ms'), ('num', 2.0)]),
              28),
             ('assign', 'pi', ('num', 3.141592653589793), 29),
             ('assign',
              'G2',
              ('mul',
               ('mul', ('var', 'pi'), ('var', 'pi')),
               ('add',
                ('add',
                 ('mul', ('var', 'm1'), ('var', 'm1')),
                 ('mul', ('var', 'm2'), ('var', 'm2'))),
                ('mul', ('var', 'm3'), ('var', 'm3')))),
              30),
             ('decl',
              'Sf',
              ('tensor', [(8, 'invariant')]),
              ('array',
               [('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j))]),
              31),
             ('assign',
              'Vcoul_g',
              ('call',
               'coulomb',
               [('num', 1.0),
                ('var', 'G2'),
                ('var', 'Sf'),
                ('var', 's1'),
                ('var', 's2'),
                ('var', 's3')]),
              32),
             ('expr', ('var', 'Vcoul_g'), 0)]}
