EXPECTED = {'functions': {'op_O': {'params': [('W', ('tensor', [('k', 'invariant')])),
                                   ('Omega', 'ℝ')],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('mul', ('var', 'Omega'), ('var', 'W')),
                        'has_loop': False,
                        'statements': []},
               'op_L': {'params': [('W', ('tensor', [('k', 'invariant')])),
                                   ('G2c', ('tensor', [('k', 'invariant')])),
                                   ('Omega', 'ℝ')],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('mul',
                                 ('mul',
                                  ('neg', ('var', 'Omega')),
                                  ('var', 'G2c')),
                                 ('var', 'W')),
                        'has_loop': False,
                        'statements': []},
               'op_Linv': {'params': [('W', ('tensor', [('k', 'invariant')])),
                                      ('G2c', ('tensor', [('k', 'invariant')])),
                                      ('Omega', 'ℝ')],
                           'return_type': ('tensor', [('k', 'invariant')]),
                           'body': ('mul',
                                    ('div',
                                     ('div', ('var', 'W'), ('var', 'safe_G2c')),
                                     ('neg', ('var', 'Omega'))),
                                    ('var', 'nonzero_f')),
                           'has_loop': False,
                           'statements': [('body_assign',
                                           'nonzero',
                                           ('call',
                                            'gt',
                                            [('var', 'G2c'), ('num', 0.0)])),
                                          ('body_assign',
                                           'nonzero_f',
                                           ('mul',
                                            ('var', 'nonzero'),
                                            ('num', 1.0))),
                                          ('body_assign',
                                           'safe_G2c',
                                           ('add',
                                            ('var', 'G2c'),
                                            ('mul',
                                             ('sub',
                                              ('num', 1.0),
                                              ('var', 'nonzero_f')),
                                             ('num', 1.0))))]},
               'op_J': {'params': [('W', ('tensor', [('m', 'invariant')])),
                                   ('s1', 'ℕ'),
                                   ('s2', 'ℕ'),
                                   ('s3', 'ℕ')],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('div', ('var', 'flat'), ('var', 'n')),
                        'has_loop': False,
                        'statements': [('body_assign',
                                        'n',
                                        ('mul',
                                         ('mul', ('var', 's1'), ('var', 's2')),
                                         ('var', 's3'))),
                                       ('body_assign',
                                        'cube',
                                        ('call',
                                         'reshape',
                                         [('var', 'W'),
                                          ('var', 's1'),
                                          ('var', 's2'),
                                          ('var', 's3')])),
                                       ('body_assign',
                                        'spec',
                                        ('call', 'fft', [('var', 'cube')])),
                                       ('body_assign',
                                        'flat',
                                        ('call',
                                         'reshape',
                                         [('var', 'spec'), ('var', 'n')]))]},
               'op_I': {'params': [('W', ('tensor', [('m', 'invariant')])),
                                   ('s1', 'ℕ'),
                                   ('s2', 'ℕ'),
                                   ('s3', 'ℕ')],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('mul', ('var', 'flat'), ('var', 'n')),
                        'has_loop': False,
                        'statements': [('body_assign',
                                        'n',
                                        ('mul',
                                         ('mul', ('var', 's1'), ('var', 's2')),
                                         ('var', 's3'))),
                                       ('body_assign',
                                        'cube',
                                        ('call',
                                         'reshape',
                                         [('var', 'W'),
                                          ('var', 's1'),
                                          ('var', 's2'),
                                          ('var', 's3')])),
                                       ('body_assign',
                                        'field',
                                        ('call', 'ifft', [('var', 'cube')])),
                                       ('body_assign',
                                        'flat',
                                        ('call',
                                         'reshape',
                                         [('var', 'field'), ('var', 'n')]))]},
               'op_Idag': {'params': [('W', ('tensor', [('m', 'invariant')])),
                                      ('active',
                                       ('tensor', [('m', 'invariant')])),
                                      ('s1', 'ℕ'),
                                      ('s2', 'ℕ'),
                                      ('s3', 'ℕ')],
                           'return_type': ('tensor', [('k', 'invariant')]),
                           'body': ('mul',
                                    ('call',
                                     'mask_select',
                                     [('var', 'F'), ('var', 'active')]),
                                    ('var', 'n')),
                           'has_loop': False,
                           'statements': [('body_assign',
                                           'n',
                                           ('mul',
                                            ('mul',
                                             ('var', 's1'),
                                             ('var', 's2')),
                                            ('var', 's3'))),
                                          ('body_assign',
                                           'F',
                                           ('call',
                                            'op_J',
                                            [('var', 'W'),
                                             ('var', 's1'),
                                             ('var', 's2'),
                                             ('var', 's3')]))]},
               'op_Jdag': {'params': [('W', ('tensor', [('k', 'invariant')])),
                                      ('active',
                                       ('tensor', [('m', 'invariant')])),
                                      ('n', 'ℕ'),
                                      ('s1', 'ℕ'),
                                      ('s2', 'ℕ'),
                                      ('s3', 'ℕ')],
                           'return_type': ('tensor', [('p', 'invariant')]),
                           'body': ('div',
                                    ('call',
                                     'op_I',
                                     [('var', 'W_full'),
                                      ('var', 's1'),
                                      ('var', 's2'),
                                      ('var', 's3')]),
                                    ('var', 'n')),
                           'has_loop': False,
                           'statements': [('body_assign',
                                           'W_full',
                                           ('call',
                                            'mask_embed',
                                            [('var', 'W'),
                                             ('var', 'active'),
                                             ('var', 'n')]))]}},
 'classes': {},
 'program': [('func_def', 'op_O'),
             ('func_def', 'op_L'),
             ('func_def', 'op_Linv'),
             ('func_def', 'op_J'),
             ('func_def', 'op_I'),
             ('func_def', 'op_Idag'),
             ('func_def', 'op_Jdag'),
             ('assign', 's1', ('num', 2), 52),
             ('assign', 's2', ('num', 2), 53),
             ('assign', 's3', ('num', 2), 54),
             ('assign', 'n', ('num', 8), 55),
             ('assign', 'Omega', ('num', 8.0), 56),
             ('assign', 'ms', ('call', 'arange', [('var', 'n')]), 58),
             ('assign',
              'm1',
              ('call',
               'mod',
               [('call', 'floor', [('div', ('var', 'ms'), ('num', 4.0))]),
                ('num', 2.0)]),
              59),
             ('assign',
              'm2',
              ('call',
               'mod',
               [('call', 'floor', [('div', ('var', 'ms'), ('num', 2.0))]),
                ('num', 2.0)]),
              60),
             ('assign',
              'm3',
              ('call', 'mod', [('var', 'ms'), ('num', 2.0)]),
              61),
             ('assign', 'c', ('num', 3.141592653589793), 62),
             ('assign',
              'G2',
              ('mul',
               ('mul', ('var', 'c'), ('var', 'c')),
               ('add',
                ('add',
                 ('mul', ('var', 'm1'), ('var', 'm1')),
                 ('mul', ('var', 'm2'), ('var', 'm2'))),
                ('mul', ('var', 'm3'), ('var', 'm3')))),
              63),
             ('assign',
              'active',
              ('call', 'le', [('var', 'G2'), ('num', 10.0)]),
              64),
             ('assign',
              'G2c',
              ('call', 'mask_select', [('var', 'G2'), ('var', 'active')]),
              65),
             ('decl',
              'W_real',
              ('tensor', [(8, 'invariant')]),
              ('array',
               [('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 2), ('complex', 1j)),
                ('add', ('num', 0), ('complex', 3j)),
                ('add', ('neg', ('num', 1)), ('complex', 0j)),
                ('add', ('num', 2), ('complex', 0j)),
                ('sub', ('num', 1), ('complex', 1j)),
                ('add', ('num', 0), ('complex', 0j)),
                ('add', ('num', 3), ('complex', 2j))]),
              68),
             ('assign',
              'W_spec',
              ('call',
               'op_J',
               [('var', 'W_real'),
                ('var', 's1'),
                ('var', 's2'),
                ('var', 's3')]),
              69),
             ('assign',
              'W_back',
              ('call',
               'op_I',
               [('var', 'W_spec'),
                ('var', 's1'),
                ('var', 's2'),
                ('var', 's3')]),
              70),
             ('expr', ('var', 'W_real'), 0),
             ('expr', ('var', 'W_back'), 0),
             ('expr',
              ('call', 'op_O', [('var', 'W_real'), ('var', 'Omega')]),
              0),
             ('decl',
              'W_active',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('add', ('num', 0), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j))]),
              78),
             ('assign',
              'LW',
              ('call',
               'op_L',
               [('var', 'W_active'), ('var', 'G2c'), ('var', 'Omega')]),
              79),
             ('assign',
              'LinvLW',
              ('call',
               'op_Linv',
               [('var', 'LW'), ('var', 'G2c'), ('var', 'Omega')]),
              80),
             ('expr', ('var', 'W_active'), 0),
             ('expr', ('var', 'LW'), 0),
             ('expr', ('var', 'LinvLW'), 0),
             ('decl',
              'W_ones',
              ('tensor', [(8, 'invariant')]),
              ('array',
               [('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 1), ('complex', 0j))]),
              86),
             ('assign',
              'W_idag',
              ('call',
               'op_Idag',
               [('var', 'W_ones'),
                ('var', 'active'),
                ('var', 's1'),
                ('var', 's2'),
                ('var', 's3')]),
              87),
             ('assign',
              'W_jdag',
              ('call',
               'op_Jdag',
               [('var', 'W_idag'),
                ('var', 'active'),
                ('var', 'n'),
                ('var', 's1'),
                ('var', 's2'),
                ('var', 's3')]),
              88),
             ('expr', ('var', 'W_idag'), 0),
             ('expr', ('var', 'W_jdag'), 0)]}
