EXPECTED = {'functions': {'lda_x': {'params': [('n', ('tensor', [('k', 'invariant')]))],
                         'return_type': ('tensor',
                                         [(2, 'invariant'),
                                          ('k', 'invariant')]),
                         'body': ('array', [('var', 'ex'), ('var', 'vx')]),
                         'has_loop': False,
                         'statements': [('body_assign',
                                         'pi',
                                         ('num', 3.141592653589793)),
                                        ('body_assign',
                                         'slater',
                                         ('mul',
                                          ('div',
                                           ('neg', ('num', 3.0)),
                                           ('num', 4.0)),
                                          ('pow',
                                           ('div',
                                            ('num', 3.0),
                                            ('mul',
                                             ('num', 2.0),
                                             ('var', 'pi'))),
                                           ('div',
                                            ('num', 2.0),
                                            ('num', 3.0))))),
                                        ('body_assign',
                                         'rs',
                                         ('pow',
                                          ('div',
                                           ('num', 3.0),
                                           ('mul',
                                            ('mul',
                                             ('num', 4.0),
                                             ('var', 'pi')),
                                            ('var', 'n'))),
                                          ('div', ('num', 1.0), ('num', 3.0)))),
                                        ('body_assign',
                                         'ex',
                                         ('div',
                                          ('var', 'slater'),
                                          ('var', 'rs'))),
                                        ('body_assign',
                                         'vx',
                                         ('mul',
                                          ('div', ('num', 4.0), ('num', 3.0)),
                                          ('var', 'ex')))]},
               'lda_c_chachiyo': {'params': [('n',
                                              ('tensor',
                                               [('k', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [(2, 'invariant'),
                                                   ('k', 'invariant')]),
                                  'body': ('array',
                                           [('var', 'ec'), ('var', 'vc')]),
                                  'has_loop': False,
                                  'statements': [('body_assign',
                                                  'pi',
                                                  ('num', 3.141592653589793)),
                                                 ('body_assign',
                                                  'a',
                                                  ('neg', ('num', 0.01554535))),
                                                 ('body_assign',
                                                  'b',
                                                  ('num', 20.4562557)),
                                                 ('body_assign',
                                                  'rs',
                                                  ('pow',
                                                   ('div',
                                                    ('num', 3.0),
                                                    ('mul',
                                                     ('mul',
                                                      ('num', 4.0),
                                                      ('var', 'pi')),
                                                     ('var', 'n'))),
                                                   ('div',
                                                    ('num', 1.0),
                                                    ('num', 3.0)))),
                                                 ('body_assign',
                                                  'ec',
                                                  ('mul',
                                                   ('var', 'a'),
                                                   ('call',
                                                    'log',
                                                    [('add',
                                                      ('add',
                                                       ('num', 1.0),
                                                       ('div',
                                                        ('var', 'b'),
                                                        ('var', 'rs'))),
                                                      ('div',
                                                       ('var', 'b'),
                                                       ('pow',
                                                        ('var', 'rs'),
                                                        ('num', 2.0))))]))),
                                                 ('body_assign',
                                                  'vc',
                                                  ('add',
                                                   ('var', 'ec'),
                                                   ('div',
                                                    ('mul',
                                                     ('mul',
                                                      ('var', 'a'),
                                                      ('var', 'b')),
                                                     ('add',
                                                      ('num', 2.0),
                                                      ('var', 'rs'))),
                                                    ('mul',
                                                     ('num', 3.0),
                                                     ('add',
                                                      ('add',
                                                       ('var', 'b'),
                                                       ('mul',
                                                        ('var', 'b'),
                                                        ('var', 'rs'))),
                                                      ('pow',
                                                       ('var', 'rs'),
                                                       ('num', 2.0)))))))]},
               'lda_c_vwn': {'params': [('n',
                                         ('tensor', [('k', 'invariant')]))],
                             'return_type': ('tensor',
                                             [(2, 'invariant'),
                                              ('k', 'invariant')]),
                             'body': ('array', [('var', 'ec'), ('var', 'vc')]),
                             'has_loop': False,
                             'statements': [('body_assign',
                                             'pi',
                                             ('num', 3.141592653589793)),
                                            ('body_assign',
                                             'A',
                                             ('num', 0.0310907)),
                                            ('body_assign',
                                             'b',
                                             ('num', 3.72744)),
                                            ('body_assign',
                                             'c',
                                             ('num', 12.9352)),
                                            ('body_assign',
                                             'x0',
                                             ('neg', ('num', 0.10498))),
                                            ('body_assign',
                                             'rs',
                                             ('pow',
                                              ('div',
                                               ('num', 3.0),
                                               ('mul',
                                                ('mul',
                                                 ('num', 4.0),
                                                 ('var', 'pi')),
                                                ('var', 'n'))),
                                              ('div',
                                               ('num', 1.0),
                                               ('num', 3.0)))),
                                            ('body_assign',
                                             'sqrt_rs',
                                             ('call', 'sqrt', [('var', 'rs')])),
                                            ('body_assign',
                                             'denom',
                                             ('add',
                                              ('add',
                                               ('var', 'rs'),
                                               ('mul',
                                                ('var', 'b'),
                                                ('var', 'sqrt_rs'))),
                                              ('var', 'c'))),
                                            ('body_assign',
                                             'Q',
                                             ('call',
                                              'sqrt',
                                              [('sub',
                                                ('mul',
                                                 ('num', 4.0),
                                                 ('var', 'c')),
                                                ('pow',
                                                 ('var', 'b'),
                                                 ('num', 2.0)))])),
                                            ('body_assign',
                                             'f_at_x0',
                                             ('div',
                                              ('mul',
                                               ('var', 'b'),
                                               ('var', 'x0')),
                                              ('add',
                                               ('add',
                                                ('pow',
                                                 ('var', 'x0'),
                                                 ('num', 2.0)),
                                                ('mul',
                                                 ('var', 'b'),
                                                 ('var', 'x0'))),
                                               ('var', 'c')))),
                                            ('body_assign',
                                             'f3',
                                             ('div',
                                              ('mul',
                                               ('num', 2.0),
                                               ('add',
                                                ('mul',
                                                 ('num', 2.0),
                                                 ('var', 'x0')),
                                                ('var', 'b'))),
                                              ('var', 'Q'))),
                                            ('body_assign',
                                             'lin',
                                             ('add',
                                              ('mul',
                                               ('num', 2.0),
                                               ('var', 'sqrt_rs')),
                                              ('var', 'b'))),
                                            ('body_assign',
                                             'atan_term',
                                             ('call',
                                              'atan',
                                              [('div',
                                                ('var', 'Q'),
                                                ('var', 'lin'))])),
                                            ('body_assign',
                                             'ec',
                                             ('mul',
                                              ('var', 'A'),
                                              ('sub',
                                               ('add',
                                                ('call',
                                                 'log',
                                                 [('div',
                                                   ('var', 'rs'),
                                                   ('var', 'denom'))]),
                                                ('mul',
                                                 ('div',
                                                  ('mul',
                                                   ('num', 2.0),
                                                   ('var', 'b')),
                                                  ('var', 'Q')),
                                                 ('var', 'atan_term'))),
                                               ('mul',
                                                ('var', 'f_at_x0'),
                                                ('add',
                                                 ('call',
                                                  'log',
                                                  [('div',
                                                    ('pow',
                                                     ('sub',
                                                      ('var', 'sqrt_rs'),
                                                      ('var', 'x0')),
                                                     ('num', 2.0)),
                                                    ('var', 'denom'))]),
                                                 ('mul',
                                                  ('var', 'f3'),
                                                  ('var', 'atan_term'))))))),
                                            ('body_assign',
                                             'tt',
                                             ('add',
                                              ('pow',
                                               ('var', 'lin'),
                                               ('num', 2.0)),
                                              ('pow',
                                               ('var', 'Q'),
                                               ('num', 2.0)))),
                                            ('body_assign',
                                             'vc',
                                             ('sub',
                                              ('var', 'ec'),
                                              ('mul',
                                               ('div',
                                                ('mul',
                                                 ('var', 'sqrt_rs'),
                                                 ('var', 'A')),
                                                ('num', 6.0)),
                                               ('sub',
                                                ('sub',
                                                 ('sub',
                                                  ('div',
                                                   ('num', 2.0),
                                                   ('var', 'sqrt_rs')),
                                                  ('div',
                                                   ('var', 'lin'),
                                                   ('var', 'denom'))),
                                                 ('div',
                                                  ('mul',
                                                   ('num', 4.0),
                                                   ('var', 'b')),
                                                  ('var', 'tt'))),
                                                ('mul',
                                                 ('var', 'f_at_x0'),
                                                 ('sub',
                                                  ('sub',
                                                   ('div',
                                                    ('num', 2.0),
                                                    ('sub',
                                                     ('var', 'sqrt_rs'),
                                                     ('var', 'x0'))),
                                                   ('div',
                                                    ('var', 'lin'),
                                                    ('var', 'denom'))),
                                                  ('div',
                                                   ('mul',
                                                    ('num', 4.0),
                                                    ('add',
                                                     ('mul',
                                                      ('num', 2.0),
                                                      ('var', 'x0')),
                                                     ('var', 'b'))),
                                                   ('var', 'tt'))))))))]}},
 'classes': {},
 'program': [('func_def', 'lda_x'),
             ('func_def', 'lda_c_chachiyo'),
             ('func_def', 'lda_c_vwn'),
             ('decl',
              'n_test',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('add', ('num', 0.5), ('complex', 0j)),
                ('add', ('num', 1.0), ('complex', 0j)),
                ('add', ('num', 2.0), ('complex', 0j)),
                ('add', ('num', 4.0), ('complex', 0j))]),
              50),
             ('assign', 'ex_vx', ('call', 'lda_x', [('var', 'n_test')]), 51),
             ('assign',
              'ec_vc',
              ('call', 'lda_c_chachiyo', [('var', 'n_test')]),
              52),
             ('assign',
              'ec_vc_vwn',
              ('call', 'lda_c_vwn', [('var', 'n_test')]),
              53),
             ('expr', ('var', 'ex_vx'), 0),
             ('expr', ('var', 'ec_vc'), 0),
             ('expr', ('var', 'ec_vc_vwn'), 0)]}
